In [1]:
import numpy as np

In [2]:
def sigmoid(z):
    """
    Compute the sigmoid of z

    Arguments:
    z -- A scalar or numpy array of any size.

    Return:
    s -- sigmoid(z)
    """

    ### START CODE HERE ### (≈ 1 line of code)
    s = 1 / (1 + np.exp(-z))
    ### END CODE HERE ###
    
    return s

In [4]:
w, b, X, Y = np.array([[1.],[2.]]), 2., np.array([[1.,2.,-1.],[3.,4.,-3.2]]), np.array([[1,0,1]])
sigmoid(np.dot(w.T, X))

array([[9.99088949e-01, 9.99954602e-01, 6.10879359e-04]])

In [6]:
np.zeros((1,2))

array([[0., 0.]])

In [19]:
a.shape

(1, 3)

In [20]:
b.shape

(2, 1)

In [21]:
a*b

array([[1, 2, 3],
       [2, 4, 6]])

In [12]:
a.shape
b.shape

(2, 1)

In [30]:
a = np.random.randn(4, 3) 
b = np.random.randn(3, 2) 

(1, 5)

In [25]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(4, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (4,2) 

In [5]:
c

array([[-0.23655245,  0.81642495, -0.75209689],
       [ 0.31908842, -0.05940537, -0.01012529],
       [-0.22624209, -0.03264323,  0.04753246],
       [-0.01277918, -0.57571314, -0.23271845]])